"""
outreach_review.py — Gray Horizons Enterprise
Emails a formatted review digest of all pending outreach drafts to YOU.

After receiving the email:
  1. Open outreach_queue.csv
  2. Change approved_to_send from NO to YES for prospects you want to contact
  3. Run: python outreach_sender.py

NEVER sends emails to prospects automatically.
Only sends a digest to YOUR review address.
"""

import os
import smtplib
import pandas as pd
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from dotenv import load_dotenv

load_dotenv()

DATA_DIR   = os.getenv("DATA_DIR", os.path.dirname(os.path.abspath(__file__)))
QUEUE_FILE = os.path.join(DATA_DIR, "outreach_queue.csv")

# --- Load credentials from .env ---
SMTP_HOST     = os.getenv("SMTP_HOST", "smtp.gmail.com")
SMTP_PORT     = int(os.getenv("SMTP_PORT", "587"))
SENDER_EMAIL  = os.getenv("SENDER_EMAIL")        # your Gmail address
SENDER_PASS   = os.getenv("SENDER_APP_PASSWORD")  # Gmail App Password
REVIEW_EMAIL  = os.getenv("REVIEW_EMAIL")         # where the digest goes (your inbox)


def build_digest(df: pd.DataFrame) -> tuple[str, str]:
    """Builds plain-text and HTML versions of the review digest."""
    count = len(df)

    # ---- Plain text ----
    plain_lines = [
        f"Gray Horizons Enterprise — Outreach Review Digest",
        f"{'=' * 52}",
        f"{count} draft message(s) are waiting for your approval.",
        f"",
        f"To approve a message:",
        f"  1. Open outreach_queue.csv",
        f"  2. Set approved_to_send = YES for the rows you want sent",
        f"  3. Run: python outreach_sender.py",
        f"",
        f"{'=' * 52}",
        f"",
    ]
    for i, (_, row) in enumerate(df.iterrows(), 1):
        plain_lines += [
            f"--- DRAFT {i} of {count} ---",
            f"Company : {row['company']}",
            f"Website : {row.get('website', '')}",
            f"Email   : {row['email'] if row['email'] else '(not found — use contact page)'}",
            f"Subject : {row.get('subject', 'HOA outreach')}",
            f"",
            row['message'],
            f"",
            f"{'- ' * 26}",
            f"",
        ]
    plain_text = "\n".join(plain_lines)

    # ---- HTML ----
    html_rows = ""
    for i, (_, row) in enumerate(df.iterrows(), 1):
        email_display = row['email'] if row['email'] else "<em>(not found — use contact page)</em>"
        msg_html = row['message'].replace('\n', '<br>')
        website = row.get('website', '')
        subject = row.get('subject', 'HOA outreach')
        html_rows += f"""
        <div style="border:1px solid #ddd; border-radius:6px; padding:18px; margin-bottom:24px;">
          <h3 style="margin-top:0; color:#1a1a2e;">Draft {i} of {count}</h3>
          <table style="font-size:14px; border-collapse:collapse; width:100%;">
            <tr><td style="padding:4px 8px; font-weight:bold; width:90px;">Company</td>
                <td style="padding:4px 8px;">{row['company']}</td></tr>
            <tr><td style="padding:4px 8px; font-weight:bold;">Website</td>
                <td style="padding:4px 8px;"><a href="{website}">{website}</a></td></tr>
            <tr><td style="padding:4px 8px; font-weight:bold;">Email</td>
                <td style="padding:4px 8px;">{email_display}</td></tr>
            <tr><td style="padding:4px 8px; font-weight:bold;">Subject</td>
                <td style="padding:4px 8px;">{subject}</td></tr>
          </table>
          <div style="margin-top:12px; background:#f7f7f7; padding:14px; border-radius:4px;
                      font-size:14px; white-space:pre-wrap; line-height:1.6;">{row['message']}</div>
        </div>
        """

    html = f"""
    <html><body style="font-family:Arial, sans-serif; max-width:700px; margin:auto; color:#222;">
      <h2 style="color:#1a1a2e;">Gray Horizons Enterprise — Outreach Review Digest</h2>
      <p style="background:#fff3cd; padding:12px; border-radius:4px; border:1px solid #ffc107;">
        <strong>{count} draft message(s)</strong> are waiting for your approval.<br><br>
        To approve:<br>
        1. Open <strong>outreach_queue.csv</strong><br>
        2. Set <code>approved_to_send = YES</code> for the rows you want sent<br>
        3. Run: <code>python outreach_sender.py</code>
      </p>
      <hr>
      {html_rows}
      <p style="color:#888; font-size:12px;">
        This digest was generated by the Gray Horizons Enterprise outreach agent.<br>
        No emails have been sent to prospects. All sending requires your manual approval.
      </p>
    </body></html>
    """
    return plain_text, html


def send_digest(plain_text: str, html: str, count: int):
    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"[GHE Review] {count} Outreach Draft(s) Awaiting Your Approval"
    msg["From"]    = SENDER_EMAIL
    msg["To"]      = REVIEW_EMAIL

    msg.attach(MIMEText(plain_text, "plain"))
    msg.attach(MIMEText(html, "html"))

    with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
        server.ehlo()
        server.starttls()
        server.login(SENDER_EMAIL, SENDER_PASS)
        server.sendmail(SENDER_EMAIL, REVIEW_EMAIL, msg.as_string())


def run():
    # Validate credentials are loaded
    missing = [k for k, v in {
        "SENDER_EMAIL": SENDER_EMAIL,
        "SENDER_APP_PASSWORD": SENDER_PASS,
        "REVIEW_EMAIL": REVIEW_EMAIL,
    }.items() if not v]
    if missing:
        print(f"[ERROR] Missing credentials in .env: {', '.join(missing)}")
        print("        Copy .env.example to .env and fill in your details.")
        return

    try:
        df = pd.read_csv(QUEUE_FILE)
    except FileNotFoundError:
        print(f"[ERROR] {QUEUE_FILE} not found. Run outreach_generator.py first.")
        return

    pending = df[df["status"] == "pending"].copy()

    if pending.empty:
        print("[INFO] No pending drafts found in outreach_queue.csv.")
        return

    print(f"[INFO] Building digest for {len(pending)} pending draft(s)...")
    plain_text, html = build_digest(pending)

    print(f"[INFO] Sending digest to {REVIEW_EMAIL}...")
    try:
        send_digest(plain_text, html, len(pending))
        print(f"\n[DONE] Digest sent to {REVIEW_EMAIL}")
        print(f"       Review the email, then update outreach_queue.csv and run:")
        print(f"       python outreach_sender.py")
    except Exception as exc:
        print(f"[ERROR] Failed to send digest: {exc}")
        print("        Check your SMTP credentials in .env")


if __name__ == "__main__":
    run()
